# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYFb19gDD4ilm_XXgJpr6mTbnYfMugb8
"""

import random

responses = {
    "hotel_timings": [
        "Our hotel is open from mrg 5 to eve 10. You can check-in anytime!",
        "We have round-the-clock service. Feel free to check-in whenever you arrive.",
        "Our front desk is available 24 hours a day for check-in and assistance."
        "for couples we charge extra amount "
    ],
    "food_options": [
        "We offer a variety of cuisines including Italian, Asian, and local dishes.",
        "Our restaurant serves dosa,idly,masala annam,poori,chapati,vada,couples ice cream.",
        "You'll find a range of delicious food options at our hotel's restaurant."
    ]
}

def hotel_chatbot():
    print("Hotel Chatbot: Hello! How can I assist you today?")
    while True:
        user_input = input("You: ")
        if user_input.lower() in ["exit", "bye", "goodbye"]:
            print("Hotel Chatbot: Thank you for chatting with us. Have a great day!")
            break
        if "timings" in user_input.lower():
            response = random.choice(responses["hotel_timings"])
        elif "food" in user_input.lower():
            response = random.choice(responses["food_options"])
        else:
            response = "I'm sorry, I'm not sure how to help with that."
        print("Hotel Chatbot:", response)

hotel_chatbot()

class BusSchedule:
    def __init__(self):
        self.schedule = {
            ("Place1", "Place2"): ["08:00 AM", "11:00 AM", "03:00 PM"],
            ("Place2", "Place3"): ["09:30 AM", "12:30 PM", "04:30 PM"],
            # Add more routes and timings as needed
        }

    def get_bus_timings(self, start_place, destination):
        route = (start_place, destination)
        if route in self.schedule:
            return self.schedule[route]
        else:
            return None

# Example usage
bus_schedule = BusSchedule()
start_place = "Place1"
destination = "Place2"
timings = bus_schedule.get_bus_timings(start_place, destination)

if timings:
    printf("Bus timings from {start_place} to {destination}: {', '.join(timings)}")
else:
    printf("Sorry, no bus timings found for the route {start_place} to {destination}.")